version: "3.8"
services:
  redis:
    container_name: "imagetopdf-redis"
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports: 
      - "6379:6379"
    volumes: 
      - /redis.conf:/usr/local/etc/redis/redis.conf
  go:
    container_name: "imagetopdf-api"
    environment:
      - APP_ENV=dev
      - PORT=8080
      - REDIS_URL=redis:6379
      - STORAGE_PATH=./storage/
      - ALLOWED_EXTENSIONS=jpg,jpeg,png
      - HOST=http://localhost
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"